# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_order.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import system_common_pb2 as system__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='system_order.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12system_order.proto\x1a\x13system_common.proto\"|\n\x16\x41llocate_Order_Request\x12\x10\n\x08order_id\x18\x01 \x02(\t\x12!\n\x0bwasher_type\x18\x02 \x02(\x0e\x32\x0c.Washer_Type\x12\x10\n\x08quantity\x18\x03 \x02(\x05\x12\x1b\n\x08\x63ustomer\x18\x04 \x02(\x0b\x32\t.Customer\"\xa7\x01\n\x17\x41llocate_Order_Response\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x0c\n\x04nick\x18\x03 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t\x12\r\n\x05level\x18\x05 \x01(\x02\x12\x11\n\tlongitude\x18\x06 \x01(\x02\x12\x10\n\x08latitude\x18\x07 \x01(\x02\x12\x1f\n\nerror_code\x18\x08 \x02(\x0e\x32\x0b.Error_Code\".\n\x14Order_Finish_Request\x12\x16\n\x0e\x63ustomer_phone\x18\x01 \x02(\t\"w\n\x13\x41llocate_Order_Push\x12\x1b\n\x08\x63ustomer\x18\x01 \x02(\x0b\x32\t.Customer\x12\x10\n\x08order_id\x18\x02 \x02(\t\x12\x10\n\x08quantity\x18\x03 \x02(\x05\x12\x1f\n\nerror_code\x18\x04 \x02(\x0e\x32\x0b.Error_Code')
  ,
  dependencies=[system__common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ALLOCATE_ORDER_REQUEST = _descriptor.Descriptor(
  name='Allocate_Order_Request',
  full_name='Allocate_Order_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='Allocate_Order_Request.order_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='washer_type', full_name='Allocate_Order_Request.washer_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='Allocate_Order_Request.quantity', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='customer', full_name='Allocate_Order_Request.customer', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=167,
)


_ALLOCATE_ORDER_RESPONSE = _descriptor.Descriptor(
  name='Allocate_Order_Response',
  full_name='Allocate_Order_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Allocate_Order_Response.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone', full_name='Allocate_Order_Response.phone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nick', full_name='Allocate_Order_Response.nick', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avatar', full_name='Allocate_Order_Response.avatar', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='Allocate_Order_Response.level', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Allocate_Order_Response.longitude', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Allocate_Order_Response.latitude', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Allocate_Order_Response.error_code', index=7,
      number=8, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=337,
)


_ORDER_FINISH_REQUEST = _descriptor.Descriptor(
  name='Order_Finish_Request',
  full_name='Order_Finish_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_phone', full_name='Order_Finish_Request.customer_phone', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=385,
)


_ALLOCATE_ORDER_PUSH = _descriptor.Descriptor(
  name='Allocate_Order_Push',
  full_name='Allocate_Order_Push',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer', full_name='Allocate_Order_Push.customer', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='order_id', full_name='Allocate_Order_Push.order_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='Allocate_Order_Push.quantity', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Allocate_Order_Push.error_code', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=506,
)

_ALLOCATE_ORDER_REQUEST.fields_by_name['washer_type'].enum_type = system__common__pb2._WASHER_TYPE
_ALLOCATE_ORDER_REQUEST.fields_by_name['customer'].message_type = system__common__pb2._CUSTOMER
_ALLOCATE_ORDER_RESPONSE.fields_by_name['error_code'].enum_type = system__common__pb2._ERROR_CODE
_ALLOCATE_ORDER_PUSH.fields_by_name['customer'].message_type = system__common__pb2._CUSTOMER
_ALLOCATE_ORDER_PUSH.fields_by_name['error_code'].enum_type = system__common__pb2._ERROR_CODE
DESCRIPTOR.message_types_by_name['Allocate_Order_Request'] = _ALLOCATE_ORDER_REQUEST
DESCRIPTOR.message_types_by_name['Allocate_Order_Response'] = _ALLOCATE_ORDER_RESPONSE
DESCRIPTOR.message_types_by_name['Order_Finish_Request'] = _ORDER_FINISH_REQUEST
DESCRIPTOR.message_types_by_name['Allocate_Order_Push'] = _ALLOCATE_ORDER_PUSH

Allocate_Order_Request = _reflection.GeneratedProtocolMessageType('Allocate_Order_Request', (_message.Message,), dict(
  DESCRIPTOR = _ALLOCATE_ORDER_REQUEST,
  __module__ = 'system_order_pb2'
  # @@protoc_insertion_point(class_scope:Allocate_Order_Request)
  ))
_sym_db.RegisterMessage(Allocate_Order_Request)

Allocate_Order_Response = _reflection.GeneratedProtocolMessageType('Allocate_Order_Response', (_message.Message,), dict(
  DESCRIPTOR = _ALLOCATE_ORDER_RESPONSE,
  __module__ = 'system_order_pb2'
  # @@protoc_insertion_point(class_scope:Allocate_Order_Response)
  ))
_sym_db.RegisterMessage(Allocate_Order_Response)

Order_Finish_Request = _reflection.GeneratedProtocolMessageType('Order_Finish_Request', (_message.Message,), dict(
  DESCRIPTOR = _ORDER_FINISH_REQUEST,
  __module__ = 'system_order_pb2'
  # @@protoc_insertion_point(class_scope:Order_Finish_Request)
  ))
_sym_db.RegisterMessage(Order_Finish_Request)

Allocate_Order_Push = _reflection.GeneratedProtocolMessageType('Allocate_Order_Push', (_message.Message,), dict(
  DESCRIPTOR = _ALLOCATE_ORDER_PUSH,
  __module__ = 'system_order_pb2'
  # @@protoc_insertion_point(class_scope:Allocate_Order_Push)
  ))
_sym_db.RegisterMessage(Allocate_Order_Push)


# @@protoc_insertion_point(module_scope)
