# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_washer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='system_washer.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13system_washer.proto\"\x86\x01\n\x06Washer\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05phone\x18\x02 \x02(\t\x12\x11\n\tlongitude\x18\x03 \x01(\x02\x12\x10\n\x08latitude\x18\x04 \x01(\x02\x12\x0c\n\x04nick\x18\x05 \x01(\t\x12\r\n\x05level\x18\x06 \x01(\x02\x12\x0e\n\x06\x61vatar\x18\x07 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x08 \x01(\t\"r\n\x17\x41llocate_Washer_Request\x12\x1f\n\norder_type\x18\x01 \x02(\x0e\x32\x0b.Order_Type\x12\x11\n\tcity_code\x18\x02 \x02(\x05\x12\x11\n\tlongitude\x18\x03 \x02(\x02\x12\x10\n\x08latitude\x18\x04 \x02(\x02\"T\n\x18\x41llocate_Washer_Response\x12\x17\n\x06washer\x18\x01 \x01(\x0b\x32\x07.Washer\x12\x1f\n\nerror_code\x18\x02 \x02(\x0e\x32\x0b.Error_Code*!\n\x08Protocol\x12\x15\n\x0f\x41LLOCATE_WASHER\x10\x80\xea\x30**\n\nOrder_Type\x12\n\n\x06NORMAL\x10\x01\x12\x10\n\x0cPROFESSIONAL\x10\x02*7\n\nError_Code\x12\x0b\n\x07SUCCESS\x10\x00\x12\x1c\n\x16\x45RROR_WASHER_NOT_FOUND\x10\x80\xea\x30')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PROTOCOL = _descriptor.EnumDescriptor(
  name='Protocol',
  full_name='Protocol',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALLOCATE_WASHER', index=0, number=800000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=362,
  serialized_end=395,
)
_sym_db.RegisterEnumDescriptor(_PROTOCOL)

Protocol = enum_type_wrapper.EnumTypeWrapper(_PROTOCOL)
_ORDER_TYPE = _descriptor.EnumDescriptor(
  name='Order_Type',
  full_name='Order_Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROFESSIONAL', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=397,
  serialized_end=439,
)
_sym_db.RegisterEnumDescriptor(_ORDER_TYPE)

Order_Type = enum_type_wrapper.EnumTypeWrapper(_ORDER_TYPE)
_ERROR_CODE = _descriptor.EnumDescriptor(
  name='Error_Code',
  full_name='Error_Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_WASHER_NOT_FOUND', index=1, number=800000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=441,
  serialized_end=496,
)
_sym_db.RegisterEnumDescriptor(_ERROR_CODE)

Error_Code = enum_type_wrapper.EnumTypeWrapper(_ERROR_CODE)
ALLOCATE_WASHER = 800000
NORMAL = 1
PROFESSIONAL = 2
SUCCESS = 0
ERROR_WASHER_NOT_FOUND = 800000



_WASHER = _descriptor.Descriptor(
  name='Washer',
  full_name='Washer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Washer.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone', full_name='Washer.phone', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Washer.longitude', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Washer.latitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nick', full_name='Washer.nick', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='Washer.level', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avatar', full_name='Washer.avatar', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='Washer.address', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=158,
)


_ALLOCATE_WASHER_REQUEST = _descriptor.Descriptor(
  name='Allocate_Washer_Request',
  full_name='Allocate_Washer_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_type', full_name='Allocate_Washer_Request.order_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='city_code', full_name='Allocate_Washer_Request.city_code', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Allocate_Washer_Request.longitude', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Allocate_Washer_Request.latitude', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=274,
)


_ALLOCATE_WASHER_RESPONSE = _descriptor.Descriptor(
  name='Allocate_Washer_Response',
  full_name='Allocate_Washer_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='washer', full_name='Allocate_Washer_Response.washer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Allocate_Washer_Response.error_code', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=360,
)

_ALLOCATE_WASHER_REQUEST.fields_by_name['order_type'].enum_type = _ORDER_TYPE
_ALLOCATE_WASHER_RESPONSE.fields_by_name['washer'].message_type = _WASHER
_ALLOCATE_WASHER_RESPONSE.fields_by_name['error_code'].enum_type = _ERROR_CODE
DESCRIPTOR.message_types_by_name['Washer'] = _WASHER
DESCRIPTOR.message_types_by_name['Allocate_Washer_Request'] = _ALLOCATE_WASHER_REQUEST
DESCRIPTOR.message_types_by_name['Allocate_Washer_Response'] = _ALLOCATE_WASHER_RESPONSE
DESCRIPTOR.enum_types_by_name['Protocol'] = _PROTOCOL
DESCRIPTOR.enum_types_by_name['Order_Type'] = _ORDER_TYPE
DESCRIPTOR.enum_types_by_name['Error_Code'] = _ERROR_CODE

Washer = _reflection.GeneratedProtocolMessageType('Washer', (_message.Message,), dict(
  DESCRIPTOR = _WASHER,
  __module__ = 'system_washer_pb2'
  # @@protoc_insertion_point(class_scope:Washer)
  ))
_sym_db.RegisterMessage(Washer)

Allocate_Washer_Request = _reflection.GeneratedProtocolMessageType('Allocate_Washer_Request', (_message.Message,), dict(
  DESCRIPTOR = _ALLOCATE_WASHER_REQUEST,
  __module__ = 'system_washer_pb2'
  # @@protoc_insertion_point(class_scope:Allocate_Washer_Request)
  ))
_sym_db.RegisterMessage(Allocate_Washer_Request)

Allocate_Washer_Response = _reflection.GeneratedProtocolMessageType('Allocate_Washer_Response', (_message.Message,), dict(
  DESCRIPTOR = _ALLOCATE_WASHER_RESPONSE,
  __module__ = 'system_washer_pb2'
  # @@protoc_insertion_point(class_scope:Allocate_Washer_Response)
  ))
_sym_db.RegisterMessage(Allocate_Washer_Response)


# @@protoc_insertion_point(module_scope)
