# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='system_common.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13system_common.proto\"\x8a\x01\n\x08\x43ustomer\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12\x0c\n\x04nick\x18\x03 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x04 \x01(\t\x12\r\n\x05level\x18\x05 \x01(\x02\x12\x11\n\tcity_code\x18\x06 \x01(\x05\x12\x11\n\tlongitude\x18\x07 \x01(\x02\x12\x10\n\x08latitude\x18\x08 \x01(\x02*O\n\x0fSystem_Protocol\x12\x14\n\x0e\x41LLOCATE_ORDER\x10\x90\xb8\x31\x12\x12\n\x0c\x46INISH_ORDER\x10\x91\xb8\x31\x12\x12\n\x0c\x43\x41NCEL_ORDER\x10\x92\xb8\x31*.\n\x0f\x43lient_Protocol\x12\x1b\n\x15WASHER_ALLOCATE_ORDER\x10\xc2\xa9\x07*(\n\x0bWasher_Type\x12\x0c\n\x08PERSONAL\x10\x01\x12\x0b\n\x07\x43OMPANY\x10\x02*Q\n\x0cOrder_Status\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x0f\n\x0b\x44ISTRIBUTED\x10\x01\x12\n\n\x06\x46INISH\x10\x02\x12\t\n\x05PAYED\x10\x03\x12\x0c\n\x08\x43\x41NCELED\x10\x04*7\n\nError_Code\x12\x0b\n\x07SUCCESS\x10\x00\x12\x1c\n\x16\x45RROR_WASHER_NOT_FOUND\x10\x90\xb8\x31')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SYSTEM_PROTOCOL = _descriptor.EnumDescriptor(
  name='System_Protocol',
  full_name='System_Protocol',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALLOCATE_ORDER', index=0, number=810000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISH_ORDER', index=1, number=810001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCEL_ORDER', index=2, number=810002,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=164,
  serialized_end=243,
)
_sym_db.RegisterEnumDescriptor(_SYSTEM_PROTOCOL)

System_Protocol = enum_type_wrapper.EnumTypeWrapper(_SYSTEM_PROTOCOL)
_CLIENT_PROTOCOL = _descriptor.EnumDescriptor(
  name='Client_Protocol',
  full_name='Client_Protocol',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WASHER_ALLOCATE_ORDER', index=0, number=120002,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=245,
  serialized_end=291,
)
_sym_db.RegisterEnumDescriptor(_CLIENT_PROTOCOL)

Client_Protocol = enum_type_wrapper.EnumTypeWrapper(_CLIENT_PROTOCOL)
_WASHER_TYPE = _descriptor.EnumDescriptor(
  name='Washer_Type',
  full_name='Washer_Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PERSONAL', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPANY', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=293,
  serialized_end=333,
)
_sym_db.RegisterEnumDescriptor(_WASHER_TYPE)

Washer_Type = enum_type_wrapper.EnumTypeWrapper(_WASHER_TYPE)
_ORDER_STATUS = _descriptor.EnumDescriptor(
  name='Order_Status',
  full_name='Order_Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISTRIBUTED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISH', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCELED', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=335,
  serialized_end=416,
)
_sym_db.RegisterEnumDescriptor(_ORDER_STATUS)

Order_Status = enum_type_wrapper.EnumTypeWrapper(_ORDER_STATUS)
_ERROR_CODE = _descriptor.EnumDescriptor(
  name='Error_Code',
  full_name='Error_Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_WASHER_NOT_FOUND', index=1, number=810000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=418,
  serialized_end=473,
)
_sym_db.RegisterEnumDescriptor(_ERROR_CODE)

Error_Code = enum_type_wrapper.EnumTypeWrapper(_ERROR_CODE)
ALLOCATE_ORDER = 810000
FINISH_ORDER = 810001
CANCEL_ORDER = 810002
WASHER_ALLOCATE_ORDER = 120002
PERSONAL = 1
COMPANY = 2
DEFAULT = 0
DISTRIBUTED = 1
FINISH = 2
PAYED = 3
CANCELED = 4
SUCCESS = 0
ERROR_WASHER_NOT_FOUND = 810000



_CUSTOMER = _descriptor.Descriptor(
  name='Customer',
  full_name='Customer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Customer.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone', full_name='Customer.phone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nick', full_name='Customer.nick', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avatar', full_name='Customer.avatar', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='Customer.level', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='city_code', full_name='Customer.city_code', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Customer.longitude', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Customer.latitude', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=162,
)

DESCRIPTOR.message_types_by_name['Customer'] = _CUSTOMER
DESCRIPTOR.enum_types_by_name['System_Protocol'] = _SYSTEM_PROTOCOL
DESCRIPTOR.enum_types_by_name['Client_Protocol'] = _CLIENT_PROTOCOL
DESCRIPTOR.enum_types_by_name['Washer_Type'] = _WASHER_TYPE
DESCRIPTOR.enum_types_by_name['Order_Status'] = _ORDER_STATUS
DESCRIPTOR.enum_types_by_name['Error_Code'] = _ERROR_CODE

Customer = _reflection.GeneratedProtocolMessageType('Customer', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMER,
  __module__ = 'system_common_pb2'
  # @@protoc_insertion_point(class_scope:Customer)
  ))
_sym_db.RegisterMessage(Customer)


# @@protoc_insertion_point(module_scope)
