# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='order.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0border.proto\"(\n\x14Order_Pickup_Request\x12\x10\n\x08order_id\x18\x01 \x02(\t\"8\n\x15Order_Pickup_Response\x12\x1f\n\nerror_code\x18\x01 \x02(\x0e\x32\x0b.Error_Code\"(\n\x14Order_Cancel_Request\x12\x10\n\x08order_id\x18\x01 \x02(\t\"8\n\x15Order_Cancel_Response\x12\x1f\n\nerror_code\x18\x01 \x02(\x0e\x32\x0b.Error_Code*2\n\x08Protocol\x12\x12\n\x0cORDER_PICKUP\x10\xc0\xa9\x07\x12\x12\n\x0cORDER_CANCEL\x10\xc1\xa9\x07*T\n\x0cOrder_Status\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x0f\n\x0b\x44ISTRIBUTED\x10\x01\x12\r\n\tDELIVERED\x10\x02\x12\t\n\x05PAYED\x10\x03\x12\x0c\n\x08\x43\x41NCELED\x10\x04*;\n\nError_Code\x12\x0b\n\x07SUCCESS\x10\x00\x12 \n\x1a\x45RROR_ORDER_PICKUP_FAILURE\x10\xc0\xa9\x07')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PROTOCOL = _descriptor.EnumDescriptor(
  name='Protocol',
  full_name='Protocol',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ORDER_PICKUP', index=0, number=120000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDER_CANCEL', index=1, number=120001,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=215,
  serialized_end=265,
)
_sym_db.RegisterEnumDescriptor(_PROTOCOL)

Protocol = enum_type_wrapper.EnumTypeWrapper(_PROTOCOL)
_ORDER_STATUS = _descriptor.EnumDescriptor(
  name='Order_Status',
  full_name='Order_Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISTRIBUTED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELIVERED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PAYED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCELED', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=267,
  serialized_end=351,
)
_sym_db.RegisterEnumDescriptor(_ORDER_STATUS)

Order_Status = enum_type_wrapper.EnumTypeWrapper(_ORDER_STATUS)
_ERROR_CODE = _descriptor.EnumDescriptor(
  name='Error_Code',
  full_name='Error_Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_ORDER_PICKUP_FAILURE', index=1, number=120000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=353,
  serialized_end=412,
)
_sym_db.RegisterEnumDescriptor(_ERROR_CODE)

Error_Code = enum_type_wrapper.EnumTypeWrapper(_ERROR_CODE)
ORDER_PICKUP = 120000
ORDER_CANCEL = 120001
DEFAULT = 0
DISTRIBUTED = 1
DELIVERED = 2
PAYED = 3
CANCELED = 4
SUCCESS = 0
ERROR_ORDER_PICKUP_FAILURE = 120000



_ORDER_PICKUP_REQUEST = _descriptor.Descriptor(
  name='Order_Pickup_Request',
  full_name='Order_Pickup_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='Order_Pickup_Request.order_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=55,
)


_ORDER_PICKUP_RESPONSE = _descriptor.Descriptor(
  name='Order_Pickup_Response',
  full_name='Order_Pickup_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Order_Pickup_Response.error_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=113,
)


_ORDER_CANCEL_REQUEST = _descriptor.Descriptor(
  name='Order_Cancel_Request',
  full_name='Order_Cancel_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='Order_Cancel_Request.order_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=155,
)


_ORDER_CANCEL_RESPONSE = _descriptor.Descriptor(
  name='Order_Cancel_Response',
  full_name='Order_Cancel_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Order_Cancel_Response.error_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=213,
)

_ORDER_PICKUP_RESPONSE.fields_by_name['error_code'].enum_type = _ERROR_CODE
_ORDER_CANCEL_RESPONSE.fields_by_name['error_code'].enum_type = _ERROR_CODE
DESCRIPTOR.message_types_by_name['Order_Pickup_Request'] = _ORDER_PICKUP_REQUEST
DESCRIPTOR.message_types_by_name['Order_Pickup_Response'] = _ORDER_PICKUP_RESPONSE
DESCRIPTOR.message_types_by_name['Order_Cancel_Request'] = _ORDER_CANCEL_REQUEST
DESCRIPTOR.message_types_by_name['Order_Cancel_Response'] = _ORDER_CANCEL_RESPONSE
DESCRIPTOR.enum_types_by_name['Protocol'] = _PROTOCOL
DESCRIPTOR.enum_types_by_name['Order_Status'] = _ORDER_STATUS
DESCRIPTOR.enum_types_by_name['Error_Code'] = _ERROR_CODE

Order_Pickup_Request = _reflection.GeneratedProtocolMessageType('Order_Pickup_Request', (_message.Message,), dict(
  DESCRIPTOR = _ORDER_PICKUP_REQUEST,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:Order_Pickup_Request)
  ))
_sym_db.RegisterMessage(Order_Pickup_Request)

Order_Pickup_Response = _reflection.GeneratedProtocolMessageType('Order_Pickup_Response', (_message.Message,), dict(
  DESCRIPTOR = _ORDER_PICKUP_RESPONSE,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:Order_Pickup_Response)
  ))
_sym_db.RegisterMessage(Order_Pickup_Response)

Order_Cancel_Request = _reflection.GeneratedProtocolMessageType('Order_Cancel_Request', (_message.Message,), dict(
  DESCRIPTOR = _ORDER_CANCEL_REQUEST,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:Order_Cancel_Request)
  ))
_sym_db.RegisterMessage(Order_Cancel_Request)

Order_Cancel_Response = _reflection.GeneratedProtocolMessageType('Order_Cancel_Response', (_message.Message,), dict(
  DESCRIPTOR = _ORDER_CANCEL_RESPONSE,
  __module__ = 'order_pb2'
  # @@protoc_insertion_point(class_scope:Order_Cancel_Response)
  ))
_sym_db.RegisterMessage(Order_Cancel_Response)


# @@protoc_insertion_point(module_scope)
