# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_1_pb2 as common__1__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='order_1.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rorder_1.proto\x1a\x0e\x63ommon_1.proto\",\n\x18Processing_Order_Request\x12\x10\n\x08order_id\x18\x01 \x02(\t\"<\n\x19Processing_Order_Response\x12\x1f\n\nerror_code\x18\x01 \x02(\x0e\x32\x0b.Error_Code\"(\n\x14\x46inish_Order_Request\x12\x10\n\x08order_id\x18\x01 \x02(\t\"8\n\x15\x46inish_Order_Response\x12\x1f\n\nerror_code\x18\x01 \x02(\x0e\x32\x0b.Error_Code\"9\n\x16Order_Feedback_Request\x12\x10\n\x08order_id\x18\x01 \x02(\t\x12\r\n\x05score\x18\x02 \x02(\x05\":\n\x17Order_Feedback_Response\x12\x1f\n\nerror_code\x18\x01 \x02(\x0e\x32\x0b.Error_Code\"(\n\x14Order_Cancel_Request\x12\x10\n\x08order_id\x18\x01 \x02(\t\"8\n\x15Order_Cancel_Response\x12\x1f\n\nerror_code\x18\x01 \x02(\x0e\x32\x0b.Error_Code\"6\n\x15History_Order_Request\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"P\n\x16History_Order_Response\x12\x15\n\x05order\x18\x01 \x01(\x0b\x32\x06.Order\x12\x1f\n\nerror_code\x18\x02 \x02(\x0e\x32\x0b.Error_Code\"w\n\x13\x41llocate_Order_Push\x12\x1b\n\x08\x63ustomer\x18\x01 \x02(\x0b\x32\t.Customer\x12\x10\n\x08order_id\x18\x02 \x02(\t\x12\x10\n\x08quantity\x18\x03 \x02(\x05\x12\x1f\n\nerror_code\x18\x04 \x02(\x0e\x32\x0b.Error_Code\"&\n\x12Wechat_Pay_Request\x12\x10\n\x08order_id\x18\x01 \x02(\t\"R\n\x13Wechat_Pay_Response\x12\x1a\n\x06wechat\x18\x01 \x01(\x0b\x32\n.WechatPay\x12\x1f\n\nerror_code\x18\x02 \x02(\x0e\x32\x0b.Error_Code')
  ,
  dependencies=[common__1__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROCESSING_ORDER_REQUEST = _descriptor.Descriptor(
  name='Processing_Order_Request',
  full_name='Processing_Order_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='Processing_Order_Request.order_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=77,
)


_PROCESSING_ORDER_RESPONSE = _descriptor.Descriptor(
  name='Processing_Order_Response',
  full_name='Processing_Order_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Processing_Order_Response.error_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=139,
)


_FINISH_ORDER_REQUEST = _descriptor.Descriptor(
  name='Finish_Order_Request',
  full_name='Finish_Order_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='Finish_Order_Request.order_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=181,
)


_FINISH_ORDER_RESPONSE = _descriptor.Descriptor(
  name='Finish_Order_Response',
  full_name='Finish_Order_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Finish_Order_Response.error_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=239,
)


_ORDER_FEEDBACK_REQUEST = _descriptor.Descriptor(
  name='Order_Feedback_Request',
  full_name='Order_Feedback_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='Order_Feedback_Request.order_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='Order_Feedback_Request.score', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=298,
)


_ORDER_FEEDBACK_RESPONSE = _descriptor.Descriptor(
  name='Order_Feedback_Response',
  full_name='Order_Feedback_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Order_Feedback_Response.error_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=358,
)


_ORDER_CANCEL_REQUEST = _descriptor.Descriptor(
  name='Order_Cancel_Request',
  full_name='Order_Cancel_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='Order_Cancel_Request.order_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=400,
)


_ORDER_CANCEL_RESPONSE = _descriptor.Descriptor(
  name='Order_Cancel_Response',
  full_name='Order_Cancel_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Order_Cancel_Response.error_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=458,
)


_HISTORY_ORDER_REQUEST = _descriptor.Descriptor(
  name='History_Order_Request',
  full_name='History_Order_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='History_Order_Request.offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit', full_name='History_Order_Request.limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=514,
)


_HISTORY_ORDER_RESPONSE = _descriptor.Descriptor(
  name='History_Order_Response',
  full_name='History_Order_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='History_Order_Response.order', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='History_Order_Response.error_code', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=516,
  serialized_end=596,
)


_ALLOCATE_ORDER_PUSH = _descriptor.Descriptor(
  name='Allocate_Order_Push',
  full_name='Allocate_Order_Push',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer', full_name='Allocate_Order_Push.customer', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='order_id', full_name='Allocate_Order_Push.order_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='Allocate_Order_Push.quantity', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Allocate_Order_Push.error_code', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=717,
)


_WECHAT_PAY_REQUEST = _descriptor.Descriptor(
  name='Wechat_Pay_Request',
  full_name='Wechat_Pay_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='Wechat_Pay_Request.order_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=719,
  serialized_end=757,
)


_WECHAT_PAY_RESPONSE = _descriptor.Descriptor(
  name='Wechat_Pay_Response',
  full_name='Wechat_Pay_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wechat', full_name='Wechat_Pay_Response.wechat', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Wechat_Pay_Response.error_code', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=759,
  serialized_end=841,
)

_PROCESSING_ORDER_RESPONSE.fields_by_name['error_code'].enum_type = common__1__pb2._ERROR_CODE
_FINISH_ORDER_RESPONSE.fields_by_name['error_code'].enum_type = common__1__pb2._ERROR_CODE
_ORDER_FEEDBACK_RESPONSE.fields_by_name['error_code'].enum_type = common__1__pb2._ERROR_CODE
_ORDER_CANCEL_RESPONSE.fields_by_name['error_code'].enum_type = common__1__pb2._ERROR_CODE
_HISTORY_ORDER_RESPONSE.fields_by_name['order'].message_type = common__1__pb2._ORDER
_HISTORY_ORDER_RESPONSE.fields_by_name['error_code'].enum_type = common__1__pb2._ERROR_CODE
_ALLOCATE_ORDER_PUSH.fields_by_name['customer'].message_type = common__1__pb2._CUSTOMER
_ALLOCATE_ORDER_PUSH.fields_by_name['error_code'].enum_type = common__1__pb2._ERROR_CODE
_WECHAT_PAY_RESPONSE.fields_by_name['wechat'].message_type = common__1__pb2._WECHATPAY
_WECHAT_PAY_RESPONSE.fields_by_name['error_code'].enum_type = common__1__pb2._ERROR_CODE
DESCRIPTOR.message_types_by_name['Processing_Order_Request'] = _PROCESSING_ORDER_REQUEST
DESCRIPTOR.message_types_by_name['Processing_Order_Response'] = _PROCESSING_ORDER_RESPONSE
DESCRIPTOR.message_types_by_name['Finish_Order_Request'] = _FINISH_ORDER_REQUEST
DESCRIPTOR.message_types_by_name['Finish_Order_Response'] = _FINISH_ORDER_RESPONSE
DESCRIPTOR.message_types_by_name['Order_Feedback_Request'] = _ORDER_FEEDBACK_REQUEST
DESCRIPTOR.message_types_by_name['Order_Feedback_Response'] = _ORDER_FEEDBACK_RESPONSE
DESCRIPTOR.message_types_by_name['Order_Cancel_Request'] = _ORDER_CANCEL_REQUEST
DESCRIPTOR.message_types_by_name['Order_Cancel_Response'] = _ORDER_CANCEL_RESPONSE
DESCRIPTOR.message_types_by_name['History_Order_Request'] = _HISTORY_ORDER_REQUEST
DESCRIPTOR.message_types_by_name['History_Order_Response'] = _HISTORY_ORDER_RESPONSE
DESCRIPTOR.message_types_by_name['Allocate_Order_Push'] = _ALLOCATE_ORDER_PUSH
DESCRIPTOR.message_types_by_name['Wechat_Pay_Request'] = _WECHAT_PAY_REQUEST
DESCRIPTOR.message_types_by_name['Wechat_Pay_Response'] = _WECHAT_PAY_RESPONSE

Processing_Order_Request = _reflection.GeneratedProtocolMessageType('Processing_Order_Request', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSING_ORDER_REQUEST,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:Processing_Order_Request)
  ))
_sym_db.RegisterMessage(Processing_Order_Request)

Processing_Order_Response = _reflection.GeneratedProtocolMessageType('Processing_Order_Response', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSING_ORDER_RESPONSE,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:Processing_Order_Response)
  ))
_sym_db.RegisterMessage(Processing_Order_Response)

Finish_Order_Request = _reflection.GeneratedProtocolMessageType('Finish_Order_Request', (_message.Message,), dict(
  DESCRIPTOR = _FINISH_ORDER_REQUEST,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:Finish_Order_Request)
  ))
_sym_db.RegisterMessage(Finish_Order_Request)

Finish_Order_Response = _reflection.GeneratedProtocolMessageType('Finish_Order_Response', (_message.Message,), dict(
  DESCRIPTOR = _FINISH_ORDER_RESPONSE,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:Finish_Order_Response)
  ))
_sym_db.RegisterMessage(Finish_Order_Response)

Order_Feedback_Request = _reflection.GeneratedProtocolMessageType('Order_Feedback_Request', (_message.Message,), dict(
  DESCRIPTOR = _ORDER_FEEDBACK_REQUEST,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:Order_Feedback_Request)
  ))
_sym_db.RegisterMessage(Order_Feedback_Request)

Order_Feedback_Response = _reflection.GeneratedProtocolMessageType('Order_Feedback_Response', (_message.Message,), dict(
  DESCRIPTOR = _ORDER_FEEDBACK_RESPONSE,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:Order_Feedback_Response)
  ))
_sym_db.RegisterMessage(Order_Feedback_Response)

Order_Cancel_Request = _reflection.GeneratedProtocolMessageType('Order_Cancel_Request', (_message.Message,), dict(
  DESCRIPTOR = _ORDER_CANCEL_REQUEST,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:Order_Cancel_Request)
  ))
_sym_db.RegisterMessage(Order_Cancel_Request)

Order_Cancel_Response = _reflection.GeneratedProtocolMessageType('Order_Cancel_Response', (_message.Message,), dict(
  DESCRIPTOR = _ORDER_CANCEL_RESPONSE,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:Order_Cancel_Response)
  ))
_sym_db.RegisterMessage(Order_Cancel_Response)

History_Order_Request = _reflection.GeneratedProtocolMessageType('History_Order_Request', (_message.Message,), dict(
  DESCRIPTOR = _HISTORY_ORDER_REQUEST,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:History_Order_Request)
  ))
_sym_db.RegisterMessage(History_Order_Request)

History_Order_Response = _reflection.GeneratedProtocolMessageType('History_Order_Response', (_message.Message,), dict(
  DESCRIPTOR = _HISTORY_ORDER_RESPONSE,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:History_Order_Response)
  ))
_sym_db.RegisterMessage(History_Order_Response)

Allocate_Order_Push = _reflection.GeneratedProtocolMessageType('Allocate_Order_Push', (_message.Message,), dict(
  DESCRIPTOR = _ALLOCATE_ORDER_PUSH,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:Allocate_Order_Push)
  ))
_sym_db.RegisterMessage(Allocate_Order_Push)

Wechat_Pay_Request = _reflection.GeneratedProtocolMessageType('Wechat_Pay_Request', (_message.Message,), dict(
  DESCRIPTOR = _WECHAT_PAY_REQUEST,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:Wechat_Pay_Request)
  ))
_sym_db.RegisterMessage(Wechat_Pay_Request)

Wechat_Pay_Response = _reflection.GeneratedProtocolMessageType('Wechat_Pay_Response', (_message.Message,), dict(
  DESCRIPTOR = _WECHAT_PAY_RESPONSE,
  __module__ = 'order_1_pb2'
  # @@protoc_insertion_point(class_scope:Wechat_Pay_Response)
  ))
_sym_db.RegisterMessage(Wechat_Pay_Response)


# @@protoc_insertion_point(module_scope)
